spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gexlog
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
files:
  directory: ${FILES_DIRECTORY}