spring:
  datasource:
    url: jdbc:h2:mem:rutaseg;mode=mysql;DATABASE_TO_LOWER=TRUE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
    hibernate:
      ddl-auto: create-drop

files:
  directory: ${FILES_DIRECTORY:/resources}